##
## EPITECH PROJECT, 2020
## ARCADE
## File description:
## Makefile
##


all:
		$(MAKE) -C ./Nibbler
		$(MAKE) -C ./Solarfox

clean:
		$(MAKE) clean -C ./Nibbler
		$(MAKE) clean -C ./Solarfox

fclean:	clean
		$(MAKE) fclean -C ./Nibbler
		$(MAKE) fclean -C ./Solarfox

re:		fclean all

.PHONY:	all clean fclean re